language: minimal

services:
  - docker

before_install:
  - docker build --build-arg PHP_VERSION="7.4" -t demartis/apache-php:7.4 .
  - docker run -d -p 127.0.0.1:80:80 demartis/apache-php:7.4
  - docker ps -a

script:
  - curl -I 127.0.0.1:80/phpinfo.php
