language: minimal

services:
  - docker
  
env:
  - PHP_VERSION=7.4
  - PHP_VERSION=7.3
  - PHP_VERSION=7.2

before_install:
  - docker build --build-arg PHP_VERSION=$PHP_VERSION -t demartis/apache-php:$PHP_VERSION .
  - docker run -d -p 127.0.0.1:80:80 demartis/apache-php:$PHP_VERSION
  - docker ps -a

script:
  - curl -I 127.0.0.1:80/phpinfo.php
