#!/bin/bash

PHP_VERSION=$(echo "${DOCKER_TAG}" | cut -d "-" -f2)

if [ "${DOCKER_TAG}" == "latest" ]
then
  PHP_VERSION="7.4"
fi

docker build . --build-arg PHP_VERSION="${PHP_VERSION}" -t "${IMAGE_NAME}"